name: '"main" branch workflow'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-tsc:
    name: Lint TypeScript

    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript Compiler
        run: npm run lint:tsc

  lint-prettier:
    name: Lint Prettier

    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npm run lint:prettier

  lint-eslint:
    name: Lint ESLint

    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint:eslint

  lint-knip:
    name: Lint Knip

    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Knip
        run: npm run lint:knip

  lint-madge:
    name: Lint Madge

    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Madge
        run: npm run lint:madge

  build:
    name: Build static files
    needs: [lint-tsc, lint-prettier, lint-eslint, lint-knip, lint-madge]

    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Infer base path
        id: infer-base-path
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const repoName = "${{ github.repository }}".split('/').pop();
            const { data } = await github.request('GET /repos/${{ github.repository }}/pages');
            return data.cname
              ? '/'
              : `/${repoName}/`;
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build static files
        run: npm run build
        env:
          BASE: ${{ steps.infer-base-path.outputs.result }}

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
